esphome:
  name: esp-32-8relays

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "a8de066f54f9b8a37b566ff8dcc053e5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # IP of ESP
    static_ip: 192.168.1.50
    # IP of router
    gateway: 192.168.1.1
    # Subnet of network
    subnet: 255.255.255.0  

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-32-8Relays Fallback Hotspot"
    password: "4xNGoZg08ElY"

captive_portal:

#Ralay1
switch:
  - platform: gpio
    id: relay1
    name: "Relay1"
    pin: 33
    inverted: true

#Ralay3
  - platform: gpio
    id: relay3
    name: "Relay3"
    pin: 27
    inverted: true
    
#Ralay4
  - platform: gpio
    id: relay4
    name: "Relay4"
    pin: 13
    inverted: true

#SSR realy

  - platform: gpio
    name: "SSRRelay"
    pin: 32
    inverted: false

#CT clamp
sensor:
  - platform: adc
    id: current_sensor
    pin: GPIO36
    attenuation: 11db
    accuracy_decimals: 5
    
  - platform: ct_clamp
    sensor: current_sensor
    id: measured_power_phase1
    name: "Measured Power on Phase 1"
    sample_duration: 200ms
    update_interval: 1s
    accuracy_decimals: 3
    filters:
      - calibrate_linear:
          # Measured value of 0 maps to 0A
          - 0.008 -> 0.0
          # Known load: 4.0A
          # Value shown in logs: 0.1333A
          - 0.058 -> 4.085
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
      - lambda: return x * 235.0 / 1000;
    unit_of_measurement: "kW" 
    state_class: measurement
    device_class: power
  
  - platform: total_daily_energy
    name: "import_ct_total"
    power_id: measured_power_phase1
    unit_of_measurement: "kWh"
    id: import_ct_total
  
  - platform: aht10
    temperature:
      name: "BathroomTemperature"
    humidity:
      name: "BathroomHumidity"
    update_interval: 60s
    
i2c:
  sda: GPIO26
  scl: GPIO25
  scan: True
  id: bus_a
  
time:
  - platform: sntp
    id: my_time

