esphome:
  name: esp-8266-temperatures

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "371b74620795fc36414f475f9935759a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-8266-Temperatures"
    password: "ERRcgn8fag1H"

captive_portal:


# Example configuration entry
dallas:
  - pin: D4

# Individual sensors
sensor:
  - platform: dallas
    address: 0xdda058871e64ff28
    name: "Bedroom large"
    
  - platform: dallas
    address: 0x4100000003a83128
    name: "Bedroom small"
    
    
binary_sensor:
  - platform: gpio
    pin: D0
    name: "PIR Sensor"
    device_class: motion